Traceback (most recent call last):
  File "sink.py", line 24, in <module>
    sink = Sink()
  File "sink.py", line 14, in __init__
    self.receiver.bind("tcp://127.0.0.1:5558")
  File "zmq\backend\cython\socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address in use
